"""
Configuration for domain skills used by the resume ranking system.
"""

DOMAIN_SKILLS = {
    "web_dev": [
        "html",
        "css",
        "javascript",
        "typescript",
        "react",
        "angular",
        "vue",
        "node.js",
        "express",
        "django",
        "flask",
        "rest api",
        "graphql",
        "bootstrap",
        "tailwind",
        "mongodb",
        "mysql",
        "postgresql",
    ],
    "data_science": [
        "python",
        "r",
        "sql",
        "pandas",
        "numpy",
        "matplotlib",
        "seaborn",
        "data analysis",
        "statistics",
        "machine learning",
        "tableau",
        "power bi",
        "etl",
        "data visualization",
    ],
    "ai_ml": [
        "python",
        "machine learning",
        "deep learning",
        "tensorflow",
        "pytorch",
        "scikit-learn",
        "nlp",
        "computer vision",
        "llm",
        "transformers",
        "opencv",
        "model deployment",
        "feature engineering",
    ],
    "cyber_security": [
        "network security",
        "penetration testing",
        "ethical hacking",
        "siem",
        "soc",
        "firewalls",
        "incident response",
        "vulnerability assessment",
        "owasp",
        "kali linux",
        "wireshark",
        "cryptography",
    ],
    "cloud_devops": [
        "aws",
        "azure",
        "gcp",
        "docker",
        "kubernetes",
        "terraform",
        "jenkins",
        "ci/cd",
        "linux",
        "ansible",
        "monitoring",
        "prometheus",
        "grafana",
        "microservices",
    ],
    "mobile_dev": [
        "android",
        "ios",
        "kotlin",
        "java",
        "swift",
        "react native",
        "flutter",
        "dart",
        "mobile ui",
        "firebase",
        "rest api",
    ],
    "sde": [
        "python",
        "java",
        "c++",
        "data structures",
        "algorithms",
        "oop",
        "system design",
        "distributed systems",
        "git",
        "testing",
        "api design",
        "problem solving",
    ],
    "ui_ux": [
        "figma",
        "adobe xd",
        "wireframing",
        "prototyping",
        "user research",
        "interaction design",
        "usability testing",
        "design systems",
        "visual design",
        "accessibility",
    ],
    "blockchain": [
        "blockchain",
        "solidity",
        "ethereum",
        "smart contracts",
        "web3",
        "defi",
        "nft",
        "truffle",
        "hardhat",
        "cryptography",
        "consensus",
    ],
}

